### ISSUE TITLE
卡片不消失原因找到了

### ISSUE THREAD

**Issue by B100402352** [Yuphee/RewardLayout#6]
clearTask方法在非ui线程，在getChildCount后进入循环体，在viewG.getChildAt(j)之前正好主线程执行了remove操作成功，这时候获取到的view会为null，getTag就空指针异常，导致定时任务停掉了。这块线程同步上有问题，简单的方案可以通过catch住异常解决，根本上还是需要注意做好线程同步。

**Comment by Yuphee** [comment]
感谢，后续会跟进这块。

**Comment by Yuphee** [comment]
你还有什么其它方案不？

**Comment by B100402352** [comment]
礼物逻辑挺复杂的，这块参考了你的代码，要感谢你哈！
想到的方案比如说可以就在主线程定时clearTask，同一个线程肯定没问题。或者这个clearTask里面做判空就OK，但不确定是否还有其他异常

**Comment by Yuphee** [comment]
主线程定时clear的话这个清理的实时性要求比较高，一直做循环做判断怕影响性能；另外判空的话，也有可能下一行代码获取tag的时候为空也是有可能的，暂时先捕获异常了。

**Comment by B100402352** [comment]
嗯，可以
