### ISSUE TITLE
同一礼物送多个的时候 会出现View没被移除的情况

### ISSUE THREAD

**Issue by Felix1030** [Yuphee/RewardLayout#9]
同时送10个人一个礼物  当再次送的时候发现 只会出现少于10个的情况  追踪发现View没有被移除 导致没显示出来

**Comment by Felix1030** [comment]
目前处理方案是 load源码 新增移除View回调或者修改onComboEnd和onKickEnd位置 延时清除

**Comment by Yuphee** [comment]
> 目前处理方案是 load源码 新增移除View回调或者修改onComboEnd和onKickEnd位置 延时清除

可以把修改的代码贴出来看下吗

**Comment by Felix1030** [comment]
/**
     * 处理删除失败
     * @param giftBean FlyBean?
     */
    private fun handleDeleteFailed(giftBean: FlyBean?) {
        if (giftBean?.mType != ChatMsgType.Gift.value) return
        val flyBeans: java.util.List<GiftIdentify> = ReflectUtils.reflect(mGiftLayout).field("beans").get<java.util.List<GiftIdentify>>()
        flyBeans.clear()
        val count = mGiftLayout.childCount
        if (count > 0) {
            for (i in 0 until mGiftLayout.childCount) {
                val viewChild = mGiftLayout.getChildAt(i)
                if (viewChild is ViewGroup) {
                    for (j in 0 until viewChild.childCount) {
                        val viewChildChild = viewChild.getChildAt(j) ?: continue
                        val tag = viewChildChild.tag
                        if (tag is FlyBean) {
                            if (tag.equals(giftBean)) {
                                viewChild.removeView(viewChildChild)
                                L.e("handleDeleteFailed giftBean $giftBean")
                                L.e("handleDeleteFailed tagBean $tag")
                            }
                        }
                    }
                }
            }
        }
    }
